### ISSUE TITLE
Run proovread locally for a plant genome

### ISSUE THREAD

**Issue by PedroBarbosa** [BioInf-Wuerzburg/proovread#103]
Hello Thomas,

I've got in hands 63 SMRT cells, which account for ~65Gb of data. Genome size is around 900Mb, and we already have an Illumina based draft which we generated using high coverage short  read libraries (Hiseq 2500 (100bp), HiSeq X (150bp)).  I'm just testing 1 SMRT cell (1.01Gb, 6.3Kb mean read length), providing one short read lib (approx 17X coverage, have more than 500X in total ), but it's taking very long so far (7hours and still counting):

> grep -P 'Running mode|ked :|ning task' log*
[Mon Jun 12 11:26:52 2017] Running mode: sr

I' running in one server with 1Tb RAM and 64 CPUs available and this was my command to start with:

> proovread --keep-temporary-files --threads 30 --haplo-coverage --prefix proovread_1smrt --long-reads m170107_202050_42146_c101064092550000001823247701061777_s1_p0.fastq -s /mnt/2-msa/gnsbr/preprocessing/illumina/Q20L80-PE/BGI_ILU_DNA_PE170_CG_01_1.NoN.Q20L80_noContaminants_PE_1.fq -s /mnt/2-msa/gnsbr/preprocessing/illumina/Q20L80-PE/BGI_ILU_DNA_PE170_CG_01_1.NoN.Q20L80_noContaminants_PE_2.fq

Do you think It's reasonable to try proovread for all the SMRT, given the description above ? I didnt' run SeqChunker yet, but I imagined that for this small input I gave, that wouldn't be necessary. 

For now, I'd just want to hear your opinion, and then I could start tweaking the parameters.
Thanks in advance,
Pedro Barbosa

**Comment by thackl** [comment]
Hi Pedro,

the runtime definitely isn't encouraging. If possible, I'd like to have quick look at the full log. It might contain some more useful infos.

About your command, don't use `--haplo-coverage`, it's slow and experimental (probably doesn't do what you want anyway)

17X might be low, but in any way you should specify `--coverage 17`. Otherwise proovread will assume >40X coverage, and down-sample your short reads, which leads to more iterations. I can say more about that after I've seen the full log. Also, you don't need to prepare the "right' coverage, you can for example use libraries with a total of about 88X, and specify `--coverage 88`. Proovread will internally subsample that to reasonable values for each iteration

Not using SeqChunker should be fine in your case, just try to keep the PacBio data per run below the size of the genome.

In general, 100bp reads are rather short. If they are overlapping, consider merging them first - that gives quite a speed-up (1/2 the reads, and longer reads need lower sensitivity). Also the 150 HiSeq X reads should be faster, and overall better for correction, for the same reason. Ideally, merge those into ~250 bp reads.

**Comment by PedroBarbosa** [comment]
Hello,

I canceled the process yesterday, as I wasn't finding it reasonable. I overwrote the output folder with a new run with 5% of reads from one SMRT sampled (~8k reads), so I can't send the logs, sorry. I started now a new run using this 5% set, providing `--coverage` argument as you suggested. I'll send you the full log when/if it finishes.

Given the expected insert sizes and some previous analysis, I don't think the pairs will overlap. But I can give flash a try and report back to you.

Pedro

**Comment by PedroBarbosa** [comment]
Hello Thomas,

proovread is still running, even for this minimal long read input. That is very surprising. Please find the log files attached.

Thanks,

[log_proovread.txt](https://github.com/BioInf-Wuerzburg/proovread/files/1074454/log_proovread.txt)
[parameter.txt](https://github.com/BioInf-Wuerzburg/proovread/files/1074461/parameter.txt)




Pedro
