### ISSUE TITLE
fatal error: zlib.h: No such file or directory

### ISSUE THREAD

**Issue by Hulanyue** [BioInf-Wuerzburg/proovread#145]
Hello,
I have git clone https://........  and it is successful
but when I  run  make && make install ,there are some  problems

linux@linux-virtual-machine:~/proovread$ make && make install
git submodule init
git submodule update --force
Submodule path 'util/SeqChunker': checked out '676b02085c50d540223e5d648250e91c5749ccfe'
Submodule path 'util/SeqFilter': checked out 'add13966d77f7d348368883213e156fc7034abc9'
Submodule path 'util/bwa': checked out 'a0aadf47802aa45e5157562ee3f7099fe4b823af'
cd util/bwa && make
make[1]: Entering directory '/home/linux/proovread/util/bwa'
gcc -c -g -Wall -Wno-unused-function -O2 -DHAVE_PTHREAD -DUSE_MALLOC_WRAPPERS  utils.c -o utils.o
utils.c:33:10: fatal error: zlib.h: No such file or directory
 #include <zlib.h>
          ^~~~~~~~
compilation terminated.
make[1]: *** [Makefile:24: utils.o] Error 1
make[1]: Leaving directory '/home/linux/proovread/util/bwa'
make: *** [Makefile:19: util] Error 2

How can I solve this problem?

**Comment by Hulanyue** [comment]
I  also have a problem : 
when I git clone https://........  ,there are not these files: .gitignore , .gitmodules ,   .pullapprove ,  .travis.yml  

will it have an impact?

**Comment by thackl** [comment]
You are missing the "zlib" library on your system. It's a basic compression library that can be easily installed on most linux distributions. On Ubuntu, for example, something like `sudo apt install zliblg zliblg-dev`.

Regarding the missing `.*` files. If they are truely missing, that would be a problem. However, I think that they are there, because otherwise no git commands should work in the first place. In Linux files starting with `.` are usually hidden when listing them with default commands. Try `ls -A` in the directory, and they should appear.
