### ISSUE TITLE
"--sample" command incompatible with samtools version 1.18

### ISSUE THREAD

**Issue by dence** [BioInf-Wuerzburg/proovread#2]
When I run the "--sample" command to see whether proovread installed correctly, I get the following error:

~/applications/proovread/bin/proovread --sample
[Mon Mar 30 14:02:25 2015] Reading core config
[Mon Mar 30 14:02:25 2015] Reading command line options
[Mon Mar 30 14:02:25 2015] Logging parameter to `pr-Fa/pr-Fa.parameter.log`
[Mon Mar 30 14:02:25 2015] Checking short read files
  
F.antasticus_short.fq
  Detected FASTQ format
  Estimated short read length: 100 +-0
  Estimating approximate number of short reads: 50.0k

[Mon Mar 30 14:02:25 2015] Checking required binaries

[main] unrecognized command '--version'
#------------------------------------------------------------------------------#
[Mon Mar 30 14:02:25 2015] Couldn't determine version of samtools, at least 1.1 
required
	Exited at 'main'
	'/home/dence/applications/proovread/bin/proovread', line 2022
	Last call 'main::check_binary'
	'/home/dence/applications/proovread/bin/proovread', line 656

maybe the "--version" command was in samtools 1.1, but is no longer maintained?

**Comment by thackl** [comment]
To my knowledge, there is no samtools-1.18... The latest releases are samtools-1.1 and samtools-1.2. But there is samtools-*0.1.18* (which was the second to last alpha release). That's probably the version you have. You will have to upgrade to be able to run proovread.

I did not know though that obviously samtools-0.1.18 does not support --version. I will try to capture this in future version in order to generate a more helpful error message.
