### ISSUE TITLE
Questions on run time of Hsg, normalization, and reason for adaptation

### ISSUE THREAD

**Issue by csuliweilong** [BioInf-Wuerzburg/proovread#26]
Hi @thackl 

From the paper, the run time of proovread on Hsg dataset is 2288d and 1009 for proovread def and proovread norm respectively. It confused me that why did you conduct the experiment for so long time. How do you calculate the run time?

Since the runtime of proovread norm on Hsg is about half of proovread def. I suppose the normalization of Hsg SRs is to sample the SRs in order to reduce the total data size with even coverage. Is my understanding correct?

As for Hst dataset, since the throughput of proovread norm is much smaller than proovread adapt, while the run time is much longer. Why adaptation causes the result change? Why use adaptation version of proovread for trancriptome dataset?

Best

Weilong

**Comment by thackl** [comment]
The runtime is the theoretical value for single core runtime. Of course, we did not wait 5 years, but we distributed and parallelized the jobs on a cluster, but used single core runtime as a comparable runtime parameter.

Regarding normalization, this is not a sampling with even coverage - proovread uses sampling internally and samples in each run, but normalization is rather the opposite. Based on kmer counts, you identify repetitive reads and reduce the number of these reads, assuming they carry redundant information (http://ivory.idyll.org/blog/what-is-diginorm.html).

About Hst, you must have misread the table. We did not run proovread norm on the Hst set, only default and adapted, and adapted increased throughput from 48% to 70%. This is because the adapted run handled low coverage transcripts much better, which in genomic sets are not expected and are often lost with default settings.

Nevertheless, you should not read to much into the statistics provided in the paper.  We did these computations at the end of 2013/early 2014. Since then, a lot has changed in proovread, in particular, we changed the mapper from SHRiMP2 to BWA MEM. The current version is much faster and also shows some different behaviour with respect to chunk sizes, repeats, etc...

Cheers
Thomas

**Comment by csuliweilong** [comment]
Thank you for the detailed answer!
