### ISSUE TITLE
What is latest stable version

### ISSUE THREAD

**Issue by mimarsh2** [BioInf-Wuerzburg/proovread#32]
I am installing this software in a shared HPC environment.  Should I pull the 2.12 tag or should I pull master and if so what version is it?  I see a recent change bumping the version to 2.13.9, but changes have been made since the.  I want to make sure the researchers know exactly what version of code they are working with.

**Comment by thackl** [comment]
The latest version is proovread-2.13.10. But you caught me there, proper versioning is a pain, and I did push some minor changes without updating the main version. Fortunately, the beauty about git is, you don't have to rely on inconsistent versioning and lazy programmers - pull the master and use the commit (78e1d98) rather than a version string to refer to the exact version you are using.
