### ISSUE TITLE
"-P" not support full path

### ISSUE THREAD

**Issue by pengchy** [BioInf-Wuerzburg/proovread#4]
Hi, I want to define the absolute path to the "-P" parameter, but failed. Currently, it had to output to the current work directory.

======================================
~/soft/01.NGS_data_process/proovread-master/bin/proovread -l /path/to/S1.fastq.gz.sub.001.fq  -s /path/to/NormalizedTenTiss.fq -P /path/to/S1.fastq.gz.sub.001.fq/
[Sat May  9 09:08:34 2015] Reading core config
[Sat May  9 09:08:34 2015] Reading command line options
#------------------------------------------------------------------------------#
  No such file or directory: `/path/to/S1.fastq.gz.sub.001.fq/path/to/S1.fastq.gz.sub.001.fq/.parameter.log`
        Exited at 'main'
        '/panfs/home/kang/yangpc//soft/01.NGS_data_process/proovread-master/bin/proovre
ad', line 387

**Comment by thackl** [comment]
Hi pengchy,

thanks for reporting. Yes, I did a rather lazy implementation there. -p currently does not support path information. I already have this on my todo list and will fix it in the next release. Let me know if this is critical to you and you need an immediate fix. Otherwise you hope you can manage with the current setup.

Cheers
Thomas

**Comment by thackl** [comment]
Hi pengchy,

I implemented full path support for the prefix option.

Thanks again making me aware of the issue.
