### ISSUE TITLE
bwa-proovreed very slow... expected?

### ISSUE THREAD

**Issue by bwlang** [BioInf-Wuerzburg/proovread#42]
I'm attempting to correct a large number of pacbio reads (~ 160Gbase) with unitigs from CA and about 70X illumina (~ 1B 150bp PE reads).
I split the pacbio reads into 8585 chunks as suggested in your manual.

The unitig process went quickly and masked  53.4%

Of course the illumina reads will take much longer since there are so many of these, but i didn't expect it to be *this* slow (now running for > 6000 seconds now)

[M::mem_process_seqs] Processed 194934 reads in 778.570 CPU sec, 195.182 real sec

is this expected? 
I'm calculating 11 days per chunk - at this rate it'll be about 2000 days on my cluster.

The process does not look I/O bound - which I expected, instead it seems to be cpu bound
/mnt/home/langhorst/src/proovread/bin/../util/bwa/bwa-proovread mem -b 20 -l 300 -T 2.5 -Y -L 30,30 -A 5 -D 0 -w 40 -k 12 -y 20 -E 4,3 -B 11 -a -r 1 -O 2,1 -W 20 -t 4 deer_1/dazzler-utg/deer_1.masked.fa /dev/fd/0

Are these settings expected for this application?

I wonder about that -a... could this be very expensive in the context of repeats.
Does the algorithm really need all alignments to be reported?

**Comment by thackl** [comment]
Hi Brad,

the recommendation regarding chunk size in the manual is outdated. With 
the latest versions of proovread, the rule of thumb is:

Use chunks as large as possible - limit is either RAM of your cluster 
nodes or the size of your genomes. Chunks should not exceed 1X coverage 
of the genome. Also, max --threads.

The very small chunks only make sense, if you need to customize runtime 
due to per job runtime limits or similar.

-a unfortunately, is required for good results. The problem is, that the 
alignment score is primarily driven by the local error read in a pacbio 
read. Consider two regions of high similarity (domains, motifs, 
repeats..). If for a short region of 100bp one pacbio read only has 10% 
errors, while the other read with the same conserved region has 20% 
errors, all short reads will be aligned to the read with lower error 
rate, regardless of their true origin.

To speed up things further, if possible, merge overlapping Illumina 
reads prior to correction. FLASh for example, would do the job.

Also, based on your Illumina stats, I am assuming you are working with a 
genome of at least 2GB in size, so probably highly repetitive. For 
large, repetitive genomes, I recommend digitally normalized short read 
sets for correction. This reduces runtime usually by several fold (have 
a look at bbnorm.sh of the BBMAP package)

Also, while the unitig mapping step is quick and in general should help 
improve correction and runtime, I have experienced that particularly for 
large genomes that does not always hold true. Runtime is often the same 
and results tend to be inferior. Therefore, I cannot really recommend 
using unitigs in your case.
