### ISSUE TITLE
Proovread Output

### ISSUE THREAD

**Issue by rakeshponnala** [BioInf-Wuerzburg/proovread#45]
Hello Author, 

I have tried using proovread for one of our low coverage pacbio data. My question is related to proovread output. When I submit pacbio reads ( Number of pacbio reads = 5889). From the application, I get 
pb-001.parameter.log
pb-001.ignored.tsv
pb-001.untrimmed.fq
pb-001.chim.tsv
5630181 Feb 21 23:14 pb-001.trimmed.fq
pb-001.trimmed.fa

I counted the Number of reads for pb-001.untrimmed.fq and pb-001.trimmed.fq. 

For: pb-001.untrimmed.fq 
Total No of reads = 4815 

For: pb-001.trimmed.fq 
Total No of reads = 2607

If I understand correctly both of the files have corrected reads. However the No of reads vary and the N50 vary quiet significantly. My question would be, which file of reads should I use for downstream analysis for example: denovo Assembly or Gap filling.

Thanks.

**Comment by thackl** [comment]
Untrimmed reads comprise uncorrected (regions that did not have 
any/enough Illumina reads mapped) and corrected regions

u: uncorrected, C: corrected

untrimmed read:
uuuuCCCCCCCuuuuCCCCCCCCCCCCCCuuuu

results in trimmed reads:
CCCCCCC
CCCCCCCCCCCCCC

You will have to choose, which one to use based on application: Since 
uncorrected regions are likely to have > 20% error, you should use 
trimmed reads for assembly (which is error sensitive). If you want to 
scaffold / map reads to identify structural differences, untrimmed reads 
might work as well, yet uncorrected regions might also be chimeric 
joins, so using trimmed reads is always safer.

Trimming chops up reads in smaller parts, hence N50 drops can be 
considerable - cutting a read in the middle halves the N50, although it 
might just have removed a couple of bases

Getting less reads in trimmed than untrimmed output is worrisome. I 
suspect, that you loose a lot of data during trimming (too short pieces 
<500bp are also removed). This suggests that correction does not work 
well on your data. If you can send me the complete log and some more 
information about your project, I might be able to give you some more 
advice. You can contact me directly by email if you like (see profile 
for address)

Cheers
Thomas

**Comment by rakeshponnala** [comment]
Thanks Thomas. I have emailed you the log file.
