### ISSUE TITLE
Tips for correcting nanopore reads

### ISSUE THREAD

**Issue by cmorganl** [BioInf-Wuerzburg/proovread#49]
I'm working with nanopore sequence data and I'm wondering if you have some tips for reparameterizing the config file to better suit the error profile of nanopore data. Can the scoring scheme of proovread bwa be modified much? I'm particularly interested in the fields for bwa-sr and bwa-sr-finish under *mapper settings*.

The HiSeq coverage is ~10-15X, though coverage is highly uneven throughout the genome.

Thanks!

**Comment by thackl** [comment]
Hi,

correcting nanopore with proovread is difficult. I have run some very preliminary tests, and even with  very high sensitivity, I did only get alignments to some very interspersed regions. It is especially difficult, if you only have  100bp HiSeq reads. Merged overlapping HiSeqs work a bit better, but useful results, you will only get from using longer MiSeq reads. Nanopore error rate is just to high for generating 100bp alignments with bwa.

Cheers
Thomas

**Comment by cmorganl** [comment]
Thanks, Thomas.

**Comment by dvera** [comment]
Any progress on this since recent improvements in nanopore accuracy?

**Comment by thackl** [comment]
To be honest, I haven't looked at it lately. It'll probably work better, but I'm not sure if proovread would be the right tool to use for that anyway. PacBio correction works particularly well because it's almost exclusively Indels, whereas homologous regions in the genomes at hand often mostly differ by substitutions - which gives a lot of discriminatory power. With nanopore, even with lower error rates, it's be harder to make a good decisions.
