### ISSUE TITLE
Identifying trimmed reads that arise from the same read and interpreting substring information

### ISSUE THREAD

**Issue by thefantasticdron** [BioInf-Wuerzburg/proovread#69]
Hello,

I have two general questions:

1. I read in another issue that proovread outputs trimmed reads on separate lines. I've been looking through my own proovread data set and I haven't been able to find any examples of trimmed reads. Could you tell me how I could identify which proovread reads arise from the same uncorrected long read? For example, suppose I have a read with identifier "@read1". What would the header lines for the trimmed reads in the FASTA file look like?

2. I also noticed that proovread outputs which substring the corrected reads correspond to in the uncorrected reads. In one instance I found that the substring information read something like "SUBSTR: 1091, 412". Does this mean that the corrected read corresponds to the reverse complement of the original uncorrected read? As well, suppose we have the substring information "SUBSTR: 412, 1091". Does the substring in the original uncorrected read include base 1091?

Thank you,
Sean

**Comment by thackl** [comment]
Hi Sean,

1. If a read is split into multiple fragments during trimming, the read IDs will be appended with .1/.2/.., so header for `@read1` would become @read1.1, @read1.2 ...

2. Proovread uses perl-style substring format, with the first number indicating the offset from the start off the read (0-based) and the second number indicating the length of the substring, rather than "start,end" coordinates.

Cheers
Thomas

**Comment by thefantasticdron** [comment]
Thank you!
