### ISSUE TITLE
3 questions about proovread

### ISSUE THREAD

**Issue by gengyuncong** [BioInf-Wuerzburg/proovread#85]
Hi Thomas,

I'm using proovread to correct my PacBio reads and I have some questions.

First,
I have about 200 GB Illumina reads for error correction in FASTQ format. However, the disk space is quite limited and I wonder if I could convert them to FASTA format for error correction so that about 100 GB will be saved. Will the accuracy or contiguity be affected? Or is there any tools that allows me to provide proovread with compressed files?

Second,
I wonder why the masked ratio decreases in last cycle? Will the pre-masked regions be further corrected or trimmed in last cycle?
Here is my result:
[Thu Oct 13 10:11:30 2016] Running mode: sr
[Thu Oct 13 10:53:10 2016] Running task bwa-sr-1
[Thu Oct 13 20:42:52 2016] Masked : 28.9%
[Thu Oct 13 20:42:52 2016] Running task bwa-sr-2
[Fri Oct 14 06:41:23 2016] Masked : 45.5%
[Fri Oct 14 06:41:23 2016] Running task bwa-sr-3
[Fri Oct 14 17:09:22 2016] Masked : 54.3%
[Fri Oct 14 17:09:22 2016] Running task bwa-sr-4
[Sat Oct 15 03:17:13 2016] Masked : 61.4%
[Sat Oct 15 03:17:13 2016] Running task bwa-sr-5
[Sat Oct 15 14:21:18 2016] Masked : 65.7%
[Sat Oct 15 14:21:18 2016] Running task bwa-sr-6
[Sun Oct 16 01:22:39 2016] Masked : 68.8%
[Sun Oct 16 01:22:42 2016] Running task bwa-sr-finish
[Sun Oct 16 06:13:17 2016] Masked : 24.2%

Third,
I corrected 115Mb PacBio reads with 14Gb Illumina short reads (about 7 X coverage since the estimated genome size is 2 Gb) and I don't specify coverage in command line and I found that the throughput is only 24.2%. Is it because the short reads have too low coverage? 

Thank you for your time,
Geng Yuncong

**Comment by thackl** [comment]
1. You can use proovread with short reads in FASTA format. It does not affect correction. Reading from compressed files, unfortunately is not supported - mainly because proovread samples on-the-fly from the provided files, and sampling gets a lot harder, if the data is compressed.
2.  Before the last step, all previously masked regions will be unmasked. And than all reads are mapped again with high specificity and stricter masking settings. The drop is most likely due to the low coverage of your illumina data. You should also checkt the amount data in the .trimmed.fq file. That can be more than the masked file, especially if coverage is low.

**Comment by gengyuncong** [comment]
Hi Thomas,

I tried with 50 X Illumina data and it worked quite well.
Here is my result:
[Wed Oct 19 11:43:27 2016] Running mode: mr
[Wed Oct 19 11:55:44 2016] Running task bwa-mr-1
[Thu Oct 20 15:43:24 2016] Masked : 80.5%
[Thu Oct 20 15:43:24 2016] Running task bwa-mr-2
[Fri Oct 21 09:04:31 2016] Masked : 88.8%
[Fri Oct 21 09:04:31 2016] Running task bwa-mr-3
[Fri Oct 21 19:52:31 2016] Masked : 90.3%
[Fri Oct 21 19:52:34 2016] Running task bwa-mr-finish
[Sat Oct 22 02:03:55 2016] Masked : 83.5%

Thank you for your help!
Geng Yuncong

**Comment by thackl** [comment]
Happy to hear that things are working now!
