### ISSUE TITLE
How can I intelligent use proovread to correct Full-length (FL) transcripts

### ISSUE THREAD

**Issue by nikou123456** [BioInf-Wuerzburg/proovread#87]
Hi thackl, 
   Sorry to bother, but I have several problem about the proovread usage.
Q1: Full-length (FL) transcripts generated by pbtranscript.py with proovread using corrected using Illumina SR reads（Paired-edn，125bp）. before correction all SRs were quality trimmed using sickle (https://github.com/najoshi/sickle) and normalized using the normalize-by-median.py script of the khmer package. In addition，I don’t have a reference genome，but the genome approximately  1,763.9MB. I don't know whether the following command is reasonable.or not .
I will use the command :
```
# SRs files were quality trimmed using sickle
sickle pe -f input_file1_1.fastq -r input_file1_2.fastq -t illumina \
 -o trimmed_output_file1_1.fastq -p trimmed_output_file1_2.fastq \
 -s trimmed_singles_file1.fastq
# SRs file2 were quality trimmed using sickle
sickle pe -f input_file2_1.fastq -r input_file2_2.fastq -t illumina \
 -o trimmed_output_file2_1.fastq -p trimmed_output_file2_2.fastq \
 -s trimmed_singles_file2.fastq

#normalition
interleave-reads.py trimmed_output_file1_1.fastq trimmed_output_file1_2.fastq \
 trimmed_output_file2_1.fastq trimmed_output_file2_2.fastq ….fastq -o interleave.fastq

#proovread，skip “SeqChunker”due to size of LRs is samll（full_length transcript.fasta = 60MB） 
./proovread -l ./LR/data/FL_transcript1.fasta -s ./SR/normalize/interleaved.fastq \
 --prefix ./LR/result/FL1 --threads 8  –overwrite --no-sampling
#proovread
./proovread -l ./LR/data/FL_transcript2.fasta -s ./SR/normalize/interleaved.fastq \
 --prefix ./LR/result/FL2 --threads 8  --overwrite --no-sampling
#cat
cat FL1.untrimmed.fa  FL2.untrimmed.fa  > corrected_FL.fa
```

Do I need to modify the file “proovread.cfg” like this(https://github.com/BioInf-Wuerzburg/proovread/issues/83):
```
'mode-tasks' => {
      'asm' => ['read-long', 'bwa-mr-finish']
}

proovread -c proovread-assembly.cfg --mode asm ... 
```

Q2: How can I assess the quality of the Full-length (FL) transcripts before and after error correction by the Proovreads? I don’t have a reference genome. In your paper, I saw that you have an evaluation script, take the liberty of writing to you, can you send the script to me?

Thanks a lot for your help!

**Comment by thackl** [comment]
Hi nikou,

Q1: Your commands look quite right. And unless you get some strange results, you don't need to modify your proovread.cfg.

Q2: This is a bit more complicated. My script is based on a reference as well (, though now I would just recommend to map your corrected reads to the reference with bbmap - which gives you nice stats about matches, mismatches etc.)

Without a reference, there are two things you should look at: 

1. You should assess how much of your data actually got corrected by proovread. Compare .trimmed.fq and .untrimmed.fq output  and have a look at [log-and-statistics](https://github.com/BioInf-Wuerzburg/proovread#log-and-statistics) for some more information.
2. Map your Illumina Reads onto your corrected PacBio transcripts (any mapper should do - bwa, bowtie, bbmap..), and open the results in for example [IGV](http://software.broadinstitute.org/software/igv/) and visually examine them. Regions of the transcripts without mappings are not corrected - either because they are not present in the illumina data set, or because they comprise so many errors that no short reads could be aligned. Those are the regions that get removed when going from untrimmed.fq to trimmed.fq. Every regions with read mappings should comprise no are almost no INDELS anymore, i.e. should be corrected.

**Comment by nikou123456** [comment]
Thanks a million. I really appreciate it. 

Best regards
nikou

**Comment by thackl** [comment]
You're welcome!
