### ISSUE TITLE
how to correct transcriptome PacBio reads better?

### ISSUE THREAD

**Issue by jiezhou1** [BioInf-Wuerzburg/proovread#97]
Hi thackl,

I want to correct my transcriptome PacBio reads with transcriptome Illumina reads (pair end,150bp). I know I should set --no-sampling. My data is large. I want to reduces runtime and I am not sure about two qustions.
1 I haven't use  BBMAP before,I learn that normalize short reads using bbnorm.sh of BBMAP can reduces runtime usually by several fold. Does this step ok with transcriptome data? Will it change the distribution of coverage of each transcript? If it can works, which will be better, (1)run FLASh to merge pair end reads ,and treat merged reads as single end reads to run bbnorm.sh.(2)run bbnorm.sh first ,and then merge the normalized pair end mates?
2 You said that "Chunks should not exceed 1X coverage of the genome"."The reason is that you don't want to have multiple pacbio reads from the same location in one chunk, or else they do compete for short read alignments". So, for transcriptome data ,should beless than 1X transcriptome or genome? I want set chunks as large as possible, transcriptome is much smaller, but seems more reasonable.
Thank you!

**Comment by thackl** [comment]
1) Normalization works particularly well with transcriptomic data. It reduces redundancy of reads from highly abundant transcripts (which is the largest fraction of your illumina reads), while retaining retaining reads of low abundant transcripts. To be on the safe side, I would be conservative on the cutoff for `bbnorm.sh`, i.e. set it to something like 200X. And I would go merging first (and since you are using the bbmap package I'd use `bbmerge.sh` over FLASh).
2) OK, so the competition effect is kind of worse for transcriptomes, because highly abundant transcripts will also be highly abundant in the PacBio data. So even in smaller chunks, there is a good chance for redundancy. The effect of competition is incontiguity (lower N50) and lower output (percentage masked/corrected). Frankly, the best way to analyze this is trying. For example, make 10 x 20MB chunks and one 200MB chunk of the same read set. Correct both sets and compare the stats and the runtimes...
```
SeqChunker -s 20M -l 10 -o pb-20M-%03d.fq iso-reads.fq   # 10 x 20MB chunks from file start
SeqChunker -s 200M -l 1 -o pb-200M-%03d.fq iso-reads.fq  # 1 x 200MB chunk from file start
```
Hope that helps!

**Comment by jiezhou1** [comment]
It's helpful, I‘ll try.
You are so kind~~thank you very much!!

**Comment by jiezhou1** [comment]
I correct my transcriptome data without split it into chunks, The result seems OK.
[Mon Mar 13 22:25:41 2017] Running mode: mr
[Mon Mar 13 22:27:23 2017] Running task bwa-mr-1
[Tue Mar 14 14:07:49 2017] Masked : 67.6%
[Tue Mar 14 14:07:49 2017] Running task bwa-mr-2
[Wed Mar 15 11:02:29 2017] Masked : 79.3%
[Wed Mar 15 11:02:30 2017] Running task bwa-mr-3
[Thu Mar 16 08:48:17 2017] Masked : 84.7%
[Thu Mar 16 08:48:17 2017] Running task bwa-mr-4
[Fri Mar 17 04:45:21 2017] Masked : 88.8%
[Fri Mar 17 04:45:21 2017] Running task bwa-mr-5
[Sat Mar 18 02:28:54 2017] Masked : 90.9%
[Sat Mar 18 02:29:05 2017] Running task bwa-mr-finish
[Sat Mar 18 10:18:31 2017] Masked : 78.7%
